version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_SuperMerchant
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: lhj7r7nk7e
      POSTGRES_DB: merchanci
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: ./app
    container_name: python_gus
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: merchanci
      DB_USER: gabriel
      DB_PASSWORD: lhj7r7nk7e
    volumes:
      - ./app:/app
    command: ["python","main.py"]

volumes:
  pgdata: